name:                Raytracer
version:             0.1.0.0
github:              "JakuJ/Raytracer"
license:             BSD3
author:              "Jakub Janaszkiewicz"
maintainer:          "janaszkiewicz.jakub@gmail.com"
copyright:           "2020 Jakub Janaszkiewicz"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Raytracer#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- vector
- linear
- parallel
- random
- mtl
- containers
- lens
- megaparsec >= 8.0

library:
  source-dirs: src

ghc-options:
# profiling
- -eventlog
- -fprof-auto
- -fno-prof-count-entries
# optimization
- -O2
- -flate-dmd-anal
- -fllvm
- -flate-specialise
- -optc-ffast-math
- -optc-O3
# warnings
- -fwarn-missing-signatures
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wno-unsupported-llvm-version

executables:
  Raytracer:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Raytracer
