resolver: lts-14.27
allow-newer: true
packages:
- .

extra-deps:
- accelerate-1.2.0.1
- linear-accelerate-0.6.0.0
- 'accelerate-llvm-1.0.0.0'
- 'accelerate-llvm-native-1.0.0.0'
- 'accelerate-llvm-ptx-1.0.0.0'
- 'llvm-hs-4.0.1.0'
- 'llvm-hs-pure-4.0.0.0'
flags:
    llvm-hs:
        shared-llvm: true